In [1]:
# Recurrent Neural Networks

# Part 1 - Data Preprocessing

# importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import os
# set the current working directory
os.chdir("C:/Users/Pranav/Desktop/Recurrent_Neural_Networks")

In [3]:
# import training set

dataset_train = pd.read_csv("Google_Stock_Price_Train.csv")
training_set = dataset_train.iloc[:,1:2].values

In [4]:
training_set

array([[ 325.25],
       [ 331.27],
       [ 329.83],
       ..., 
       [ 793.7 ],
       [ 783.33],
       [ 782.75]])

In [5]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range= (0,1))

training_set_scaled = sc.fit_transform(training_set)


In [6]:
training_set_scaled

array([[ 0.08581368],
       [ 0.09701243],
       [ 0.09433366],
       ..., 
       [ 0.95725128],
       [ 0.93796041],
       [ 0.93688146]])

In [7]:
# Creating a data structure with 60 timestamps and 1 output

X_train = []
y_train = []

for i in range(60,1258):
    X_train.append(training_set_scaled[i-60:i , 0])
    y_train.append(training_set_scaled[i , 0])

X_train, y_train = np.array(X_train), np.array(y_train)

In [8]:
X_train

array([[ 0.08581368,  0.09701243,  0.09433366, ...,  0.07846566,
         0.08034452,  0.08497656],
       [ 0.09701243,  0.09433366,  0.09156187, ...,  0.08034452,
         0.08497656,  0.08627874],
       [ 0.09433366,  0.09156187,  0.07984225, ...,  0.08497656,
         0.08627874,  0.08471612],
       ..., 
       [ 0.92106928,  0.92438053,  0.93048218, ...,  0.95475854,
         0.95204256,  0.95163331],
       [ 0.92438053,  0.93048218,  0.9299055 , ...,  0.95204256,
         0.95163331,  0.95725128],
       [ 0.93048218,  0.9299055 ,  0.93113327, ...,  0.95163331,
         0.95725128,  0.93796041]])

In [9]:
y_train

array([ 0.08627874,  0.08471612,  0.07454052, ...,  0.95725128,
        0.93796041,  0.93688146])

In [10]:

# Reshaping since RNN accepts only 3d shaped inputs

X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1], 1))

In [11]:

# Part 2 -- building the RNN

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout


Using TensorFlow backend.


In [12]:
# Initialising the RNN

regressor = Sequential()

In [13]:
# Adding the first LSTM layer and some dropout regularization

regressor.add(LSTM(units=50, return_sequences = True , input_shape = (X_train.shape[1], 1)))

regressor.add(Dropout(0.2))


In [14]:
# Adding second layer of LSTM and dropout regularization

regressor.add(LSTM(units=50, return_sequences = True ))

regressor.add(Dropout(0.2))

# Adding third layer of LSTM and dropout regularization

regressor.add(LSTM(units=50, return_sequences = True ))

regressor.add(Dropout(0.2))

# Adding fourth layer of LSTM and dropout regularization. Remember return_sequences = False if we don't mention

regressor.add(LSTM(units=50))

regressor.add(Dropout(0.2))

In [15]:
# Adding the output layer

regressor.add(Dense(units=1))

In [16]:

# compiling the RNN

regressor.compile(optimizer= 'adam' , loss= 'mean_squared_error')

In [17]:
# Fitting the RNN to the training set

regressor.fit(X_train, y_train, epochs= 100, batch_size= 32)

Epoch 1/100
1198/1198 [==============================] - 8s - loss: 0.0540     
Epoch 2/100
1198/1198 [==============================] - 7s - loss: 0.0059     
Epoch 3/100
1198/1198 [==============================] - 7s - loss: 0.0059     
Epoch 4/100
1198/1198 [==============================] - 7s - loss: 0.0053     
Epoch 5/100
1198/1198 [==============================] - 7s - loss: 0.0056     
Epoch 6/100
1198/1198 [==============================] - 7s - loss: 0.0041     
Epoch 7/100
1198/1198 [==============================] - 7s - loss: 0.0040     
Epoch 8/100
1198/1198 [==============================] - 7s - loss: 0.0041     
Epoch 9/100
1198/1198 [==============================] - 7s - loss: 0.0044     
Epoch 10/100
1198/1198 [==============================] - 7s - loss: 0.0040     
Epoch 11/100
1198/1198 [==============================] - 7s - loss: 0.0041     
Epoch 12/100
1198/1198 [==============================] - 7s - loss: 0.0040     
Epoch 13/100
1198/1198 [=============

In [18]:
# Making the predictions and visualising the results

# getting the real stock price of 2017

dataset_test = pd.read_csv("Google_Stock_Price_Test.csv")

real_stock_price = dataset_test.iloc[:,1:2].values

In [19]:

# Getting the predicted stock price of 2017


dataset_total = pd.concat((dataset_train['Open'], dataset_test['Open']) , axis= 0)

In [20]:
dataset_total

0       325.25
1       331.27
2       329.83
3       328.34
4       322.04
5       313.70
6       310.59
7       314.43
8       311.96
9       314.81
10      312.14
11      319.30
12      294.16
13      291.91
14      292.07
15      287.68
16      284.92
17      284.32
18      287.95
19      290.41
20      291.38
21      291.34
22      294.23
23      296.39
24      302.44
25      303.18
26      304.87
27      302.81
28      304.11
29      304.63
         ...  
1248    800.40
1249    790.22
1250    796.76
1251    795.84
1252    792.36
1253    790.90
1254    790.68
1255    793.70
1256    783.33
1257    782.75
0       778.81
1       788.36
2       786.08
3       795.26
4       806.40
5       807.86
6       805.00
7       807.14
8       807.48
9       807.08
10      805.81
11      805.12
12      806.91
13      807.25
14      822.30
15      829.62
16      837.81
17      834.71
18      814.66
19      796.86
Name: Open, dtype: float64

In [21]:
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60 : ].values

In [22]:
inputs

array([ 779.  ,  779.66,  777.71,  786.66,  783.76,  781.22,  781.65,
        779.8 ,  787.85,  798.24,  803.3 ,  795.  ,  804.9 ,  816.68,
        806.34,  801.  ,  808.35,  795.47,  782.89,  778.2 ,  767.25,
        750.66,  774.5 ,  783.4 ,  779.94,  791.17,  756.54,  755.6 ,
        746.97,  755.2 ,  766.92,  771.37,  762.61,  772.63,  767.73,
        764.26,  760.  ,  771.53,  770.07,  757.44,  744.59,  757.71,
        764.73,  761.  ,  772.48,  780.  ,  785.04,  793.9 ,  797.4 ,
        797.34,  800.4 ,  790.22,  796.76,  795.84,  792.36,  790.9 ,
        790.68,  793.7 ,  783.33,  782.75,  778.81,  788.36,  786.08,
        795.26,  806.4 ,  807.86,  805.  ,  807.14,  807.48,  807.08,
        805.81,  805.12,  806.91,  807.25,  822.3 ,  829.62,  837.81,
        834.71,  814.66,  796.86])

In [23]:
inputs = inputs.reshape(-1,1)

In [24]:
inputs

array([[ 779.  ],
       [ 779.66],
       [ 777.71],
       [ 786.66],
       [ 783.76],
       [ 781.22],
       [ 781.65],
       [ 779.8 ],
       [ 787.85],
       [ 798.24],
       [ 803.3 ],
       [ 795.  ],
       [ 804.9 ],
       [ 816.68],
       [ 806.34],
       [ 801.  ],
       [ 808.35],
       [ 795.47],
       [ 782.89],
       [ 778.2 ],
       [ 767.25],
       [ 750.66],
       [ 774.5 ],
       [ 783.4 ],
       [ 779.94],
       [ 791.17],
       [ 756.54],
       [ 755.6 ],
       [ 746.97],
       [ 755.2 ],
       [ 766.92],
       [ 771.37],
       [ 762.61],
       [ 772.63],
       [ 767.73],
       [ 764.26],
       [ 760.  ],
       [ 771.53],
       [ 770.07],
       [ 757.44],
       [ 744.59],
       [ 757.71],
       [ 764.73],
       [ 761.  ],
       [ 772.48],
       [ 780.  ],
       [ 785.04],
       [ 793.9 ],
       [ 797.4 ],
       [ 797.34],
       [ 800.4 ],
       [ 790.22],
       [ 796.76],
       [ 795.84],
       [ 792.36],
       [ 7

In [25]:
inputs = sc.transform(inputs)

In [26]:
inputs

array([[ 0.9299055 ],
       [ 0.93113327],
       [ 0.92750577],
       [ 0.94415507],
       [ 0.93876032],
       [ 0.93403527],
       [ 0.93483518],
       [ 0.9313937 ],
       [ 0.94636878],
       [ 0.96569685],
       [ 0.97510976],
       [ 0.95966962],
       [ 0.97808617],
       [ 1.        ],
       [ 0.98076494],
       [ 0.97083116],
       [ 0.98450406],
       [ 0.96054394],
       [ 0.9371419 ],
       [ 0.92841729],
       [ 0.90804747],
       [ 0.8771858 ],
       [ 0.92153434],
       [ 0.93809063],
       [ 0.93165414],
       [ 0.95254483],
       [ 0.88812412],
       [ 0.88637547],
       [ 0.87032145],
       [ 0.88563137],
       [ 0.90743359],
       [ 0.91571173],
       [ 0.89941588],
       [ 0.91805566],
       [ 0.9089404 ],
       [ 0.9024853 ],
       [ 0.89456061],
       [ 0.91600938],
       [ 0.9132934 ],
       [ 0.88979835],
       [ 0.86589404],
       [ 0.89030062],
       [ 0.90335962],
       [ 0.89642086],
       [ 0.91777662],
       [ 0

In [27]:

X_test = []


for i in range(60,80):
    X_test.append(inputs[i-60:i , 0])
    
X_test= np.array(X_test)


# Reshaping

X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1], 1))


In [28]:
X_test

array([[[ 0.9299055 ],
        [ 0.93113327],
        [ 0.92750577],
        ..., 
        [ 0.95725128],
        [ 0.93796041],
        [ 0.93688146]],

       [[ 0.93113327],
        [ 0.92750577],
        [ 0.94415507],
        ..., 
        [ 0.93796041],
        [ 0.93688146],
        [ 0.92955205]],

       [[ 0.92750577],
        [ 0.94415507],
        [ 0.93876032],
        ..., 
        [ 0.93688146],
        [ 0.92955205],
        [ 0.94731751]],

       ..., 
       [[ 0.96054394],
        [ 0.9371419 ],
        [ 0.92841729],
        ..., 
        [ 1.01045465],
        [ 1.02407173],
        [ 1.03930724]],

       [[ 0.9371419 ],
        [ 0.92841729],
        [ 0.90804747],
        ..., 
        [ 1.02407173],
        [ 1.03930724],
        [ 1.03354044]],

       [[ 0.92841729],
        [ 0.90804747],
        [ 0.8771858 ],
        ..., 
        [ 1.03930724],
        [ 1.03354044],
        [ 0.99624228]]])

In [29]:
predicted_stock_price = regressor.predict(X_test)

predicted_stock_price = sc.inverse_transform(predicted_stock_price)

In [30]:
predicted_stock_price

array([[ 771.19012451],
       [ 768.3170166 ],
       [ 769.29260254],
       [ 771.33221436],
       [ 775.08972168],
       [ 781.26226807],
       [ 786.23809814],
       [ 787.26190186],
       [ 786.71588135],
       [ 786.40679932],
       [ 786.6942749 ],
       [ 787.03033447],
       [ 787.20007324],
       [ 787.90960693],
       [ 788.84851074],
       [ 793.99291992],
       [ 801.36462402],
       [ 808.57196045],
       [ 811.23394775],
       [ 804.63452148]], dtype=float32)

In [31]:

# Visualising the results

plt.plot(real_stock_price , color = 'red' , label = "Real Google Stock Price")


plt.plot(predicted_stock_price , color = 'blue' , label = "Predicted Google Stock Price")

plt.title('Google Stock Price Prediction')

plt.xlabel('Time')

plt.ylabel('Google Stock Price')

plt.legend()

plt.show()